# GET all persons and phonebook entries.
GET http://localhost:3002/api/persons
Accept: application/json

###

# GET the information page.
GET http://localhost:3002/info
Accept: application/json

###

# GET a single person and phonebook entry.
GET http://localhost:3002/api/persons/3
Accept: application/json

###

# DELETE an entry from the phonebook.
DELETE http://localhost:3002/api/persons/63a2f65e0aa1175ef37b9cfc
Accept: application/json

###

# POST a new entry to the phonebook.
POST http://localhost:3002/api/persons
Accept: application/json
Content-Type: application/json

{
  "name": "Mert Tekin",
  "number": "0555-555-55-55"
}

###

# Failed: POST new entry without name field.
POST http://localhost:3002/api/persons
Accept: application/json
Content-Type: application/json

{
  "number": "0507-055-86-65"
}

###

# Failed: POST new entry without phone field.
POST http://localhost:3002/api/persons
Accept: application/json
Content-Type: application/json

{
  "name": "Ege Dogan Dursun"
}

###

# Failed: POST new entry with conflict in name field (already exists).
POST http://localhost:3002/api/persons
Accept: application/json
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "040-123456"
}

###

# Update: PUT a new information for a user
PUT http://localhost:3002/api/persons/63a2f61696edba163c76c345
Accept: application/json
Content-Type: application/json

{
  "name": "deneme",
  "number": "123-45678"
}

###

PUT https://mern-node-js-production.up.railway.app/api/persons/63a2f61696edba163c76c345
Accept: application/json
Content-Type: application/json

{
  "name": "deneme",
  "number": "999-999-99-91"
}